# Site Settings
title: Konrad Nowakowski Portfolio
email: konrad.x92@gmail.com
description: >-
  My portfolio website.
baseurl: /
github_username: lethiandev

# Build Settings
markdown: kramdown
collections:
  projects:
    output: true
    permalink: /:collection/:title
defaults:
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package*.json
  - tsconfig.json
